### ISSUE TITLE
Got this error ModuleNotFoundError: No module named 'inference.models'

### ISSUE THREAD

**Issue by rizkiduwinanto** [C-bowman/inference-tools#41]
I got this error ModuleNotFoundError: No module named 'inference.models', how do you fix it?

**Comment by C-bowman** [comment]
Hi @rizkiduwinanto,

The error is correct - `inference-tools` doesn't have a `models` module, so I would guess in your code you have an import line which looks like

```Python
from inference.models import [something]
```

Which will be causing the problem.

Could you post some additional information, like the full Traceback of the error? Also, which version of `inference-tools` installed do you have installed?

Thanks
