### ISSUE TITLE
New release in the pipeline?

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [C-bowman/inference-tools#7]
Hi Chris!

I saw there were some small changes since the last release (0.5.4).

Are you planning on releasing another version soon?

Nothing major but I get a lot of syntax warnings due to python 3.9.

But this commit https://github.com/C-bowman/inference-tools/commit/ba67ecc5f5db450895d3de2e44408cd46031ee4c solved it.

Cheers!

Rem

**Comment by Shimwell** [comment]
We can make a PR to automate the pypi update with a GitHub action if you like.

**Comment by RemDelaporteMathurin** [comment]
@Shimwell I can surely do something like this. This requires the action of Chris nonetheless:
- the workflow should be triggered by releases
- the version tag should be controlled by Chris too

**Comment by C-bowman** [comment]
Hi Rémi, Jon,

There is indeed a new version on the way! It's just been taking a while because it contains a lot of code across three new modules.

Work on the code itself is basically done now, so I'll merge development branch for it (likelihoods_and_priors) into master within a day or two. However it'll take a bit longer than that to do a proper release and update PyPI, since I need to update the documentation for all the new classes first. I'm hoping the release will happen within two weeks.

I'm still on Python 3.8.5 at the moment, so if you do see any other warnings pop up from changes in 3.9 let me know and I'll put in a fix before the release.

Cheers

Chris

**Comment by RemDelaporteMathurin** [comment]
Hi @C-bowman 

Thanks for reaching out.

I think the only warnings I obtained have already been fixed in the develop version of the package (though I'm not able to test it since I'm only using the pip distribution).

This is the repo where I'm using your package: https://github.com/IRFM/divHretention

and these are the warnings I obtain in the CI:

```
../../../usr/local/lib/python3.9/site-packages/inference_tools-0.5.4-py3.9.egg/inference/gp_tools.py:804
  /usr/local/lib/python3.9/site-packages/inference_tools-0.5.4-py3.9.egg/inference/gp_tools.py:804: SyntaxWarning: "is not" with a literal. Did you mean "!="?
    if len(self.y.shape) is not 2: self.y = self.y.reshape([self.y.size,1])

../../../usr/local/lib/python3.9/site-packages/inference_tools-0.5.4-py3.9.egg/inference/gp_tools.py:850
  /usr/local/lib/python3.9/site-packages/inference_tools-0.5.4-py3.9.egg/inference/gp_tools.py:850: SyntaxWarning: "is" with a literal. Did you mean "=="?
    if self.selector is 'evidence':

../../../usr/local/lib/python3.9/site-packages/inference_tools-0.5.4-py3.9.egg/inference/gp_tools.py:852
  /usr/local/lib/python3.9/site-packages/inference_tools-0.5.4-py3.9.egg/inference/gp_tools.py:852: SyntaxWarning: "is" with a literal. Did you mean "=="?
    elif self.selector is 'NNML':
```
(see here : https://app.circleci.com/pipelines/github/IRFM/divHretention/51/workflows/b8840dd6-5548-40d3-aa7c-6d98b9265f71/jobs/56 )

**Comment by C-bowman** [comment]
Hi @RemDelaporteMathurin 

Version 0.6.0 has now been released and published on PyPI, so should now be available to install via pip.

If I missed any of the syntax warning fixes do let me know, and I'll include them in a bugfix release.

Cheers,

Chris

**Comment by RemDelaporteMathurin** [comment]
Hi @C-bowman!

I'll try and update the dependencies next week and keep you posted 😄 

Thank you so much :-)
